//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseRandomEntities : DbContext
    {
        public DatabaseRandomEntities()
            : base("name=DatabaseRandomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRATOR> ADMINISTRATORs { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<INSTITUTION> INSTITUTIONs { get; set; }
        public virtual DbSet<REGION> REGIONs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<SUBJECTFACT> SUBJECTFACTs { get; set; }
        public virtual DbSet<TEST> TESTs { get; set; }
        public virtual DbSet<TestStudent> TestStudents { get; set; }
        public virtual DbSet<THEME> THEMEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
