//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRATOR
    {
        public int AdministratorID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Emailaddress { get; set; }
        public System.DateTime DateEmployed { get; set; }
        public string Active { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
