//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUITION
    {
        public int InstituitionID { get; set; }
        public int CityID { get; set; }
        public string InstituitionName { get; set; }
    
        public virtual CITY CITY { get; set; }
    }
}
