//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST()
        {
            this.TestStudents = new HashSet<TestStudent>();
        }
    
        public int TestID { get; set; }
        public int SubjectID { get; set; }
        public System.DateTime DateStarted { get; set; }
        public System.DateTime DateCompleted { get; set; }
    
        public virtual SUBJECT SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestStudent> TestStudents { get; set; }
    }
}
