//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStudent
    {
        public int ID { get; set; }
        public int TestID { get; set; }
        public int StudentID { get; set; }
        public decimal Mark { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
