//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string GUID { get; set; }
        public System.DateTime GUIDExpiry { get; set; }
        public int AdministratorID { get; set; }
        public int StudentID { get; set; }
    
        public virtual ADMINISTRATOR ADMINISTRATOR { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
